[package]
name = "cas-client"
version = "0.1.0"
authors = ["Srdan Srepfler <schrepfler@gmail.com>"]
edition = "2018"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
actix-rt = "1.0.0"
actix-web = "2.0.0-rc"